# Generated by Django 4.2.6 on 2023-10-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_rename_booking_payment_rename_service_soft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soft',
            old_name='address',
            new_name='description',
        ),
        migrations.AddField(
            model_name='soft',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.authuser'),
        ),
    ]
