export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL';

export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const CREATE_GOOD_SUCCESS = 'CREATE_GOOD_SUCCESS';
export const CREATE_GOOD_FAIL = 'CREATE_GOOD_FAIL';

export const UPDATE_GOOD_SUCCESS = 'UPDATE_GOOD_SUCCESS';
export const UPDATE_GOOD_FAIL = 'UPDATE_GOOD_FAIL';

export const CHECK_STAFF_SUCCESS = 'CHECK_STAFF_SUCCESS';
export const CHECK_STAFF_FAIL = 'CHECK_STAFF_FAIL';

export const SAVER = 'SAVER';


export const SUCCESS_ADD = 'SUCCESS_ADD';
export const FAIL_ADD = 'FAIL_ADD';

export const ORDERS_LOAD_SUCCESS = 'ORDERS_LOAD_SUCCESS';
export const ORDERS_LOAD_FAIL = 'ORDERS_LOAD_FAIL';

